//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryNotifier.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int BATTERY_UPPER_THRESHOLD {
            get {
                return ((int)(this["BATTERY_UPPER_THRESHOLD"]));
            }
            set {
                this["BATTERY_UPPER_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int BATTERY_LOWER_THRESHOLD {
            get {
                return ((int)(this["BATTERY_LOWER_THRESHOLD"]));
            }
            set {
                this["BATTERY_LOWER_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int BATTERY_UPPER_THRESHOLD_DEFAULT {
            get {
                return ((int)(this["BATTERY_UPPER_THRESHOLD_DEFAULT"]));
            }
            set {
                this["BATTERY_UPPER_THRESHOLD_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int BATTERY_LOWER_THRESHOLD_DEFAULT {
            get {
                return ((int)(this["BATTERY_LOWER_THRESHOLD_DEFAULT"]));
            }
            set {
                this["BATTERY_LOWER_THRESHOLD_DEFAULT"] = value;
            }
        }
    }
}
