name: Release

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [master]
    types: 
      - completed
  push:
    branches: [ "master" ]

jobs:
  test:    
    runs-on: windows-latest  
    strategy:
        matrix:
            dotnet-version: [ '3.1.x', '6.0.x' ]
   
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish BatteryNotifier/BatteryNotifier.csproj --configuration Release -o release --no-build --no-logo
      - name: Upload
        uses: actions/upload-artifact@v3
        with: 
          name: application_artifact
          path: BatteryNotifier/release/